pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'testing parameters', name: 'myBoolean')
    } 
    stages {
        stage('Build') {
            steps {
                script {
                    if(params.myBoolean == true) {
                        currentBuild.result = 'SUCCESS'
                        return
                    } else {
                        echo 'boolean parameter: ${params.myBoolean}'
                    }
                }
                // sh 'npm install'
                echo 'Build'
            }
        }
        stage('Test') {
            steps {
                // sh './jenkins/scripts/test.sh'
                echo 'Test'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver'
                // sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
