pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // sh 'npm install'
                sayHi('Muhammed')
                echo 'Build'
            }
        }
        stage('Test') {
            steps {
                // sh './jenkins/scripts/test.sh'
                echo 'Test'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver'
                // sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh './jenkins/scripts/kill.sh'
            }
        }
    }
}

def sayHi(String name) {
    echo 'Hello ${name} from jenkins function..'
}
