pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: "testing parameters", name: "myBoolean")
    }
    stages {
        stage("Paramerters") {
            steps {
                echo "boolean parameter is : ${parameters.myBoolean}"
            }
        }
        stage('Build') {
            steps {
                echo 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver'
            }
        }
        stage('Completed') {
            steps {
                echo 'We are done!'
            }
        }
    }
}
